<footer>
    <div class="main-footer">
        <hr class="hr-footer">

        <div class="icon-footer">
            <a href="https://www.facebook.com/"><i class="fa fa-facebook-official"></i></a>
            <a href="https://twitter.com/"><i class="fa fa-twitter-square"></i></a>
            <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
            <a href="mailto:bachnhswh00470@fpt.edu.vn"><i class="fa fa-google-plus-circle"></i></a>
        </div>

        <ul class="list-inline">
            <li class="list-inline-item"><a href="index.php">Home</a></li>
            <li class="list-inline-item"><a href="market.php">Our Product</a></li>
            <li class="list-inline-item"><a href="exchange.php">Exchange</a></li>
            <li class="list-inline-item"><a href="about.php">About Us</a></li>
        </ul>
        <p>&copy; GameDex, Ltd. All Rights Reserved.</p>
    </div>
</footer>